### PR TITLE
support openresty xxx_by_lua_block syntax

### PR DESCRIPTION
**Pull request by virusdefender**
https://github.com/openresty/lua-nginx-module

this is only a demo code and proposal about lexing the lua block, do you have any suggestions?

### CODE REVIEW

**Comment by tufanbarisyildirim** [comment]
Hey @virusdefender  appreciate your contribution! 
It seem that it will stop parsing at first closing curly bracket `}` in lua. 
And tests does not do any assertion, can you please fix?

**Comment by virusdefender** [comment]
> It seem that it will stop parsing at first closing curly bracket } in lua.

I updated the test case, it seems there is no problem.

This pr is only a workaround and it's used to show my idea to solve this problem.
It's not fully tested, maybe it should not be merged.

the full support is not easy, according to the openresty source code https://github.com/openresty/lua-nginx-module/blob/1c1bcfeb9276c6dfc9b038a6fa779e7e4b605bc9/src/ngx_http_lua_directive.c#L1344

**Review by tufanbarisyildirim — COMMENTED** [review]
> > It seem that it will stop parsing at first closing curly bracket } in lua.
> 
> I updated the test case, it seems there is no problem.
> 
> This pr is only a workaround and it's used to show my idea to solve this problem.
> It's not fully tested, maybe it should not be merged.
> 
> the full support is not easy, according to the openresty source code https://github.com/openresty/lua-nginx-module/blob/1c1bcfeb9276c6dfc9b038a6fa779e7e4b605bc9/src/ngx_http_lua_directive.c#L1344

yeah we don't have to implement full lua parsing, that's more than enough, thanks for the great work. 

would you like to implement `token.LuaCode` too ? here: https://github.com/tufanbarisyildirim/gonginx/pull/5/files/c517eab3b92742ad1ca47b6390cbcd43d1ccc74e#diff-9addfd7def9e75f9cc35434dba385b46f66574c76dfbbba8a5deb064ce0fff50R138

**Comment by tufanbarisyildirim** [comment]
@virusdefender any update with this?

**Pull request closed without merging**
